# coding=utf-8

name_mapping = {
    "1. Amy": "Amy",
    "4. Amy": "Amy",
    "4. Sheldon": "Sheldon",
    "2.": "Others",
    "3.": "Others",
    "5.": "Others",
    "Actor": "Others",
    "Actress": "Others",
    "Announcement": "Others",
    "Announcer": "Others",
    "Answerphone": "Others",
    "Assistant": "Others",
    "Auditioneer": "Others",
    "Baggage Clerk": "Others",
    "Barber": "Others",
    "Barman": "Others",
    "Barry Kripke": "Barry",
    "Barry’s Siri": "Others",
    "Bermadette": "Bernadette",
    "Bill Nye": "Bill",
    "Blonde Girl": "Others",
    "Both": "Others",
    "Boys": "Others",
    "Brent Spinner": "Brent",
    "Butterfly Girl": "Others",
    "Child": "Others",
    "Clerk": "Others",
    "Cosmonaut": "Others",
    "DMV Lady": "Others",
    "Dead Mrs Wolowitz": "Howard’s Mother",
    "Director": "Others",
    "Doctor": "Others",
    "Dr Hofstadter": "Leonard’s Mother",
    "Dr Koothrapalli": "Raj’s Father",
    "Dr Koothrappali": "Raj’s Father",
    "Elderly Korean Gentleman": "Others",
    "Employee": "Others",
    "Employment Office Assistant": "Others",
    "Everybody": "Others",
    "Everyone": "Others",
    "Fat Leonard": "Leonard",
    "Fat Leonard and Raj": ["Leonard", "Raj"],
    "Fat Raj": "Raj",
    "Fat Stuart": "Stuart",
    "Female Voice": "Others",
    "First Alien": "Others",
    "First Car Thief": "Others",
    "First Girl": "Girl",
    "Foreign Nurse": "Others",
    "Gablehauser": "Dr Gablehouser",
    "Gablehouser": "Dr Gablehouser",
    "Girl dressed as a Witch": "Girl",
    "Girl in Butterfly Costume": "Girl",
    "Girl in Hippie Costume": "Girl",
    "Girls": "Girl",
    "Guard": "Others",
    "Guy": "Others",
    "Guys in Passing Car": "Others",
    "HR Woman": "Others",
    "Headmaster": "Others",
    "Howard and Bernadette": ["Howard", "Bernadette"],
    "Howard and Raj": ["Howard", "Raj"],
    "Howatd": "Howard",
    "Ira Flatow": "Ira",
    "Judge": "Others",
    "Katee Sackhoff": "Katee",
    "Kevn": "Kevin",
    "Kid": "Boy",
    "Korean": "Others",
    "Kripke": "Barry",
    "Lady Vet": "Others",
    "Large Black Transverstite": "Others",
    "LeVar Burton": "LeVar",
    "Leoanard": "Leonard",
    "Leonard and Howard": ["Leonard", "Howard"],
    "Lesley": "Leslie",
    "Leslie Winkle": "Leslie",
    "Man in Crowd": "Man",
    "Man in Penny’s Apartment": "Man",
    "Man in Suit": "Man",
    "Man on Screen": "Man",
    "Man with Flowers": "Man",
    "Man’s Voice": "Man",
    "Minister": "Others",
    "Mission Control": "Others",
    "Model": "Others",
    "Mr. Rostenkowski": "Mr Rostenkowski",
    "Mrs": "Woman",
    "Mrs Cooper": "Sheldon’s Mother",
    "Mrs Hofstadter": "Leonard’s Mother",
    "Mrs Koothrapalli": "Raj’s Mother",
    "Mrs Koothrappali": "Raj’s Mother",
    "Mrs Wolowitz": "Howard’s Mother",
    "NASA Guy": "Others",
    "Nathan": "Nathan Fillion",
    "Nerdy Guy": "Man",
    "Nurse": "Others",
    "Nurse Costume Girl": "Girl",
    "On-screen Sheldon": "Sheldon",
    "Owner": "Others",
    "Paramedic": "Others",
    "Past Howard": "Howard",
    "Past Leonard": "Leonard",
    "Past Penny": "Penny",
    "Past Raj": "Raj",
    "Past Sheldon": "Sheldon",
    "Penny’s Dad": "Penny’s Father",
    "Phone": "Others",
    "Photographer": "Others",
    "Policeman": "Others",
    "Psychic": "Others",
    "Ra": "Raj",
    "Radio": "Others",
    "Rai": "Raj",
    "Raj, Bernadette and Amy": ["Raj", "Bernadette", "Amy"],
    "Rajj": "Raj",
    "Raj’s Voice": "Raj",
    "Receptionist": "Others",
    "Registrar": "Others",
    "Second Alien": "Others",
    "Second Car Thief": "Others",
    "Second Girl": "Girl",
    "Security Guard": "Others",
    "Sehldon":"Sheldon",
    "Server": "Others",
    "Sgeldon":"Sheldon",
    "Shedon": "Sheldon",
    "Shelldon":"Sheldon",
    "Shldon": "Sheldon",
    "Shopkeeper": "Others",
    "Seibert": "Siebert",
    "Siri": "Others",
    "Speccy Guy": "Others",
    "Speccy Guy Behind Counter": "Others",
    "Stadium Announcer": "Others",
    "Star Trek": "Others",
    "Sweatpants": "Others",
    "TV Announcer": "Others",
    "Tattooist": "Others",
    "Tech Support Guy": "Others",
    "Theatre Staff": "Others",
    "Third Floor Janitor": "Others",
    "Together":"Others",
    "Transvestite": "Others",
    "Various": "Others",
    "Voice Inside": "Voice",
    "Voice from Outside": "Voice",
    "Voice of Spock": "Voice",
    "Waiter": "Man",
    "Waitress": "Woman",
    "Wil Wheaton": "Wil",
    "Witch": "Woman",
    "Woman Caller": "Woman",
    "Woman at Door": "Woman",
    "Zombie": "Others"
}
