# coding=utf-8

filtered_names = [
    'All',
    'Together',
    'Man',
    'Men',
    'Woman',
    'Women',
    'Girl',
    'Voice',
    'Guy',
    'Nerdy Guy',
    'Man in Suit',
    'Both',
    'First Girl',
    'Everybody',
    'Female Voice',
    'Second Girl',
    'Various',
    'Blonde Girl',
    'Man’s Voice',
    'Phone',
    'Woman Caller',
    'Voice from Outside',
    'Voice Inside',
    'Boys',
    'Girls',
    'Woman at Door',
    '1.',
    'Man in Crowd',
    'Guys in Passing Car',
    'Mrs'
]

name_mapping = {
    "1. Amy": "Amy",
    "4. Amy": "Amy",
    "4. Sheldon": "Sheldon",
    "2.": "None",
    "3.": "None",
    "5.": "None",
    "Barry Kripke": "Barry",
    "Bermadette": "Bernadette",
    "Bill Nye": "Bill",
    "Brent Spinner": "Brent",
    "Dead Mrs Wolowitz": "Howard’s Mother",
    "Dr Hofstadter": "Leonard’s Mother",
    "Dr Koothrapalli": "Raj’s Father",
    "Dr Koothrappali": "Raj’s Father",
    "Fat Leonard": "Leonard",
    "Fat Leonard and Raj": ["Leonard", "Raj"],
    "Fat Raj": "Raj",
    "Fat Stuart": "Stuart",
    "Gablehauser": "Dr Gablehouser",
    "Gablehouser": "Dr Gablehouser",
    "Howard and Bernadette": ["Howard", "Bernadette"],
    "Howard and Raj": ["Howard", "Raj"],
    "Howatd": "Howard",
    "Ira Flatow": "Ira",
    "Katee Sackhoff": "Katee",
    "Kevn": "Kevin",
    "Kripke": "Barry",
    "LeVar Burton": "LeVar",
    "Leoanard": "Leonard",
    "Leonard and Howard": ["Leonard", "Howard"],
    "Lesley": "Leslie",
    "Leslie Winkle": "Leslie",
    "Mr. Rostenkowski": "Mr Rostenkowski",
    "Mrs Cooper": "Sheldon’s Mother",
    "Mrs Hofstadter": "Leonard’s Mother",
    "Mrs Koothrapalli": "Raj’s Mother",
    "Mrs Koothrappali": "Raj’s Mother",
    "Mrs Wolowitz": "Howard’s Mother",
    "Nathan": "Nathan Fillion",
    "On-screen Sheldon": "Sheldon",
    "Past Howard": "Howard",
    "Past Leonard": "Leonard",
    "Past Penny": "Penny",
    "Past Raj": "Raj",
    "Past Sheldon": "Sheldon",
    "Penny’s Dad": "Penny’s Father",
    "Ra": "Raj",
    "Rai": "Raj",
    "Raj, Bernadette and Amy": ["Raj", "Bernadette", "Amy"],
    "Rajj": "Raj",
    "Raj’s Voice": "Raj",
    "Sehldon":"Sheldon",
    "Sgeldon":"Sheldon",
    "Shedon": "Sheldon",
    "Shelldon":"Sheldon",
    "Shldon": "Sheldon",
    "Seibert": "Siebert",
    "Wil Wheaton": "Wil"
}
